# This is a basic workflow to help you get started with Actions

name: Wiki-Sync

# Controls when the workflow will run
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: nevstop
                access_token: ${{ secrets.WIKI_SYNC_TOKEN }}
                wiki_folder: wiki
                commit_username: 'NEVSTOP'
                commit_email: 'NEVSTOP@users.noreply.github.com'
                commit_message: 'action: wiki sync'
